export const INITIAL_PROJECTS = [
  {
    id: 'stellar-build-erp',
    name: 'STELLAR-BUILD-ERP System',
    category: 'Web Application',
    shortDescription: 'STELLAR-BUILD-ERP Management System web application developed using the MERN stack.',
    description: 'A comprehensive enterprise resource planning system designed to streamline business workflows, project management, and resource allocation using modern web technologies.',
    technologies: ['MongoDB', 'Express.js', 'React', 'Node.js', 'MERN Stack'],
    imageUrl: '/assets/images/card1.gif',
    imagePath: '',
    imageAlt: 'STELLAR-BUILD-ERP System preview animation',
    githubUrl: 'https://github.com/Ushara-B/Stellar-build-ERP.git',
    liveUrl: '',
    featured: true,
    published: true,
    order: 1,
  },
  {
    id: 'note-maker',
    name: 'Note Maker',
    category: 'Mobile Application',
    shortDescription: 'Feature-rich notes app with search, category organization, and full CRUD functionality.',
    description: 'Notes Maker offers the capability to add note titles and relevant content, as well as the functionality to insert, update, and delete notes with ease. The app also includes a specific data search feature.',
    technologies: ['Flutter', 'Dart', 'SQLite', 'Mobile App'],
    imageUrl: '/assets/images/card2.gif',
    imagePath: '',
    imageAlt: 'Note Maker mobile application demo',
    githubUrl: 'https://github.com/JahanRazh/Notes-Maker_Mobile_App.git',
    liveUrl: '',
    featured: true,
    published: true,
    order: 2,
  },
  {
    id: 'fiesta-burgers',
    name: 'Fiesta Burgers',
    category: 'Mobile Application',
    shortDescription: 'Food ordering mobile app allowing users to browse menus and fully customize burgers.',
    description: 'Customers can browse our menu, pick their burger or customize their burger to their tastes: bun, burger slide option, toppings, and special requests.',
    technologies: ['Flutter', 'Dart', 'Firebase', 'UI/UX'],
    imageUrl: '/assets/images/card3.gif',
    imagePath: '',
    imageAlt: 'Fiesta Burgers food ordering application demo',
    githubUrl: 'https://github.com/JahanRazh/Food_Ordering_Mobile_App.git',
    liveUrl: '',
    featured: true,
    published: true,
    order: 3,
  },
  {
    id: 'school-information-management-system',
    name: 'School Information Management System',
    category: 'Web Application',
    shortDescription: 'Integrated software system facilitating efficient management of school operations.',
    description: 'A School Management System (SIMS) that integrates student records, academic grading, attendance tracking, and administrative workflows in a centralized portal.',
    technologies: ['PHP', 'MySQL', 'Bootstrap', 'JavaScript'],
    imageUrl: '/assets/images/card4.png',
    imagePath: '',
    imageAlt: 'School Information Management System screenshot',
    githubUrl: 'https://github.com/JahanRazh/Online-School-Information-Management-System.git',
    liveUrl: '',
    featured: false,
    published: true,
    order: 4,
  },
  {
    id: 'gem-snake',
    name: 'Gem Snake',
    category: 'Mobile Game',
    shortDescription: 'Classic snake mobile game with gems, dynamic score multiplier, and high-score tracking.',
    description: 'In this snake mobile game, players earn points by consuming gems, with each gem adding points to their score. The game keeps track of the highest score attained across multiple sessions.',
    technologies: ['Java', 'Android SDK', 'Game Development'],
    imageUrl: '/assets/images/card5.gif',
    imagePath: '',
    imageAlt: 'Gem Snake mobile game gameplay animation',
    githubUrl: 'https://github.com/JahanRazh/Snake_Mobile_Game.git',
    liveUrl: '',
    featured: false,
    published: true,
    order: 5,
  },
  {
    id: 'diet-planning-health-system',
    name: 'Diet Planning & Health Check-up System',
    category: 'Web Application',
    shortDescription: 'Online platform for customized diet plans, nutrition tracking, and health screenings.',
    description: 'An online health platform providing nutritional calculations, tailored dietary plans, and routine wellness check-up questionnaires for users seeking healthy lifestyles.',
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'PHP', 'MySQL'],
    imageUrl: '/assets/images/card7.png',
    imagePath: '',
    imageAlt: 'Diet Planning & Health Check-up System screenshot',
    githubUrl: 'https://github.com/JahanRazh/Diet_Plan_and_Health_Check-up_System..git',
    liveUrl: '',
    featured: false,
    published: true,
    order: 6,
  },
];
